{{- if include "pyrra.openshiftOauthSessionChartManaged" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyrra.fullname" . }}-session
  namespace: {{ include "pyrra.namespace" . }}
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
data:
  {{- $msg := "openshift.oauth.sessionSecret (or openshift.oauth.existingSecret) is required when openshift.oauth.enabled=true" }}
  session_secret: {{ required $msg .Values.openshift.oauth.sessionSecret | b64enc }}
{{- end -}}
