---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
  name: {{ include "pyrra.serviceAccountName" . }}
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules/status
  verbs:
  - get
- apiGroups:
  - pyrra.dev
  resources:
  - servicelevelobjectives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pyrra.dev
  resources:
  - servicelevelobjectives/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.openshift.isOpenshift }}
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses/api
  resourceNames:
  - k8s
  verbs:
  - get
  - create
  - update
{{- if .Values.openshift.openshiftOauth.enabled }}
- verbs:
  - create
  apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
- verbs:
  - create
  apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
{{- end }}
{{- end }}
