{{- if include "pyrra.mimirBasicAuthChartManaged" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyrra.fullname" . }}-mimir-basic-auth
  namespace: {{ include "pyrra.namespace" . }}
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
stringData:
  mimir-basic-auth-password: {{ .Values.mimir.basicAuth.password | quote }}
{{- end -}}
