{{- if and .Values.openshift.isOpenshift .Values.openshift.openshiftOauth.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "pyrra.fullname" . }}-sa-token
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "pyrra.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyrra.fullname" . }}
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
data:
  session_secret: |-
    {{ .Values.openshift.openshiftOauth.sessionSecret | b64enc }}
{{- end }}
