name: EditorConfig Checker

on:
  push:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2.1.0
      - name: Run editorconfig-checker
        run: |
          editorconfig-checker
