name: EditorConfig Checker

on:
  push:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
